### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by acosonic** [arzam16/mt6577_kernel_Acer_B1_A71#9]
I am not exactly sure what's the procedure and is there GUI after uploading this to B1 ?

**Comment by arzam16** [comment]
I don't understand what do you mean. What kind of GUI do you expect?

**Comment by acosonic** [comment]
Is it like this? https://www.youtube.com/watch?v=rc2XN6lUgY8 once installed?

**Comment by arzam16** [comment]
I will try to explain.

Linux is not an operating system unto itself. Linux is the kernel: the program in the system that allocates the machine’s resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. 

This repository contains Linux kernel source code for B1-A71 and nothing else. You can build the kernel and run some operating system using it. Here are the caveats:

- This device is very old and has very weak hardware
- There are no known custom Android ROMs for this device
- There are no publicly released builds of non-Android based operating systems for this device

Considering the above, you still can compile the kernel to use it with the stock Android ROM of this device _but_ there are no real advantages of this kernel compared to the stock one.

This repository is a public part of my small side project where I learn how Linux kernel works. I have necessary files for building a working [postmarketOS](https://wiki.postmarketos.org/wiki/Main_Page) distro image but they are not public and I didn't consider releasing them yet. Nevertheless, even if these files were released the system would've been barely usable, here's a quick rundown of what doesn't work: 

- bluetooth
- gps
- accelerometer
- sound (both input and output)
- camera
- hardware graphics acceleration which is vital but PowerVR decided to not release the source code of their drivers.
